### ISSUE TITLE
KeyCode.backquote注册时空指针异常

### ISSUE THREAD

**Issue by ZXQ-Kyle** [leanflutter/hotkey_manager#15]
环境：macos flutter sdk 3.0.1   hotkey_manager: ^0.1.7 

HotKey(
    KeyCode.backquote,
    modifiers: [KeyModifier.control],
    scope: HotKeyScope.system,
  )
KeyCode.backquote报错，使用KeyCode.keyQ就不会
hotkey_manager/HotkeyManagerPlugin.swift:42: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by ZXQ-Kyle** [comment]
mac上backquote对应的是grave

**Comment by lijy91** [comment]
我研究一下，看看是不是需要做个映射

**Comment by lijy91** [comment]
v0.2.0 已经直接使用了 flutter 内置的 keymap 来获取 keycode，具体看这里 https://github.com/leanflutter/hotkey_manager/pull/32#issuecomment-1974723346
