### ISSUE TITLE
Migrate to new HardwareKeyboard  class

### ISSUE THREAD

**Issue by shidenggui** [leanflutter/hotkey_manager#17]
hotkey_manger now use the depreacted RawKeyboard class, the new class is [HardwareKeyboard page](https://api.flutter.dev/flutter/services/HardwareKeyboard-class.html). 

And I found some bugs about RawKeyboard that official has said below:

Compared to [RawKeyboard](https://api.flutter.dev/flutter/services/RawKeyboard-class.html)
[RawKeyboard](https://api.flutter.dev/flutter/services/RawKeyboard-class.html) is the legacy API, and will be **deprecated and removed** in the future. It is recommended to always use [HardwareKeyboard](https://api.flutter.dev/flutter/services/HardwareKeyboard-class.html) and [KeyEvent](https://api.flutter.dev/flutter/services/KeyEvent-class.html) APIs (such as [FocusNode.onKeyEvent](https://api.flutter.dev/flutter/widgets/FocusNode/onKeyEvent.html)) to handle key events.

Behavior-wise, [RawKeyboard](https://api.flutter.dev/flutter/services/RawKeyboard-class.html) provides a less unified, less regular event model than [HardwareKeyboard](https://api.flutter.dev/flutter/services/HardwareKeyboard-class.html). For example:

* Down events might not be matched with an up event, and vice versa (the set of pressed keys is silently updated).
* The logical key of the down event might not be the same as that of the up event.
* Down events and repeat events are not easily distinguishable (must be tracked manually).
* Lock modes (such as CapsLock) only have their "enabled" state recorded. There's no way to acquire their pressing state.

**Comment by lijy91** [comment]
Migrated, Please upgrade to v0.2.0
