### ISSUE TITLE
Overriding platform-wide shortcuts?

### ISSUE THREAD

**Issue by whiplashoo** [leanflutter/hotkey_manager#3]
Tried the example app, and I wasn't able to register a new shortcut for already defined macOS-level shortcuts, for example `Command + Q `(which quits the app) or `Command + Space `(brings up Spotlight search). 

Is there any way to be able to override such keyboard combos? I am sure this is possible on other desktop apps, e.g. I can do it for iTerm or Android Studio through their keyboard preferences, so I am looking to also have that feature in my Flutter app.

**Comment by lijy91** [comment]
`hotkey_manager` uses [https://github.com/soffes/HotKey](https://github.com/soffes/HotKey) library on macOS platform, I am not sure whether it can override the system shortcut keys, I will test whether it and other similar libraries can support.

**Comment by lijy91** [comment]
Follow up in https://github.com/leanflutter/hotkey_manager/issues/10

**Comment by leedstyh** [comment]
Is the F10 on windows the same issue here?
