### ISSUE TITLE
注册应用级别的热键，在macOS上按下的时候会咚的一声

### ISSUE THREAD

**Issue by 6ag** [leanflutter/hotkey_manager#34]
就像是快捷键冲突的那种提示音，注册系统级别的不会

**Comment by Eric0x** [comment]
i had the same problem

**Comment by Zhoucheng133** [comment]
的确存在这样的问题，应该是没有聚焦，有一个比较折中的解决办法就是添加一个系统菜单：
```dart
if(Platform.isMacOS) PlatformMenuBar(
  menu: [
    // ...
  ]
)
```
详细写法：[PlatformMenuBar class - Flutter API](https://api.flutter.dev/flutter/widgets/PlatformMenuBar-class.html)

然后添加一个`shortcut`属性就好了

**Comment by lijy91** [comment]
请升级到 v0.2.0，这个版本已经做了处理，具体看这里 https://github.com/leanflutter/hotkey_manager/blob/6a223ca6225f71bb3a9add9a98a747432a02c05e/packages/hotkey_manager/lib/src/hotkey_manager.dart#L50-L86
