### ISSUE TITLE
backquote在windows上注册不能触发

### ISSUE THREAD

**Issue by ysdxz207** [leanflutter/hotkey_manager#35]
环境：windows
HotKey _hotKey = HotKey(
    KeyCode.backquote,
    modifiers: [KeyModifier.control],
    // 设置热键范围（默认为 HotKeyScope.system）
    scope: HotKeyScope.system, // 设置为应用范围的热键。
  );

dependencies:
  hotkey_manager: ^0.1.7

control+backquote不能触发，keycode换成其他的就没问题，比如换成keyQ
多台电脑测试过，均是如此。

**Comment by lijy91** [comment]
应该是 keymap 不全，0.2.0 版本已经支持
