### ISSUE TITLE
global, single non-letter key hotkeys e.g `.` or `,` don't work on Windows

### ISSUE THREAD

**Issue by wis** [leanflutter/hotkey_manager#38]
```
  HotKey(
    KeyCode.comma,
    modifiers: [],
    scope: HotKeyScope.system,
  )
  ```
  
I think the issue is because these characters are not assign to any VK_ key values here:

https://github.com/leanflutter/hotkey_manager/blob/a9d91208670c757b6e2dc69df91216820da034a8/windows/hotkey_manager_plugin.cpp#L81-L83

**Comment by lijy91** [comment]
I made some changes to keymap, see https://github.com/leanflutter/hotkey_manager/pull/32#issuecomment-1974723346
