### ISSUE TITLE
注册应用内热键（alt+s）后，触发一次后按住（alt）会一直触发

### ISSUE THREAD

**Issue by MoonBlueSky** [leanflutter/hotkey_manager#9]
# 问题
注册应用内热键（alt+s）后，触发一次后按住（alt）会一直触发
# 环境
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.18363.1556], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
[√] Android Studio (version 2021.1)
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
# 代码
本库示例代码

**Comment by lijy91** [comment]
Fixed, please update to v0.1.7
